export const ACCESS_TOKEN_SECRET = "veNRnAWe6inFuo8o2u8SLLZLjolYDmDP7SzL0YfYI";
export const SALT_WORK_FACTOR = 10;

export const status = {
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_OK: "NOT_OK",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  OK: "OK",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
}